# Generated by Django 4.2.28 on 2026-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='collaboraterequest',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
